---
title: ""
format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
---

# Further Training and Certifications

::::: columns
::: {.column width="30%"}
**ongoing**
:::

::: {.column width="70%"}
Professional Data Analyst in R and SQL  - DataCamp Verified Certification
:::
:::::

::::: columns
::: {.column width="30%"}
**ongoing**
:::

::: {.column width="70%"}
Associate Data Scientist in Python  - DataCamp Verified Certification
:::
:::::

::::: columns
::: {.column width="30%"}
**03/2025**
:::

::: {.column width="70%"}
[Azure Fundamentals](https://learn.microsoft.com/en-us/users/stefanstojkovic-0247/credentials/certification/azure-fundamentals?tab=credentials-tab) - Microsoft Certified<br> Credential ID: DF52E7938294E98C
:::
:::::

::::: columns
::: {.column width="30%"}
**02/2025**
:::

::: {.column width="70%"}
[Foundation of Generative AI](https://www.udacity.com/certificate/e/f365d39a-b7bc-11ef-aaff-7fc1f9c2c0db) - Verified Nanodegree, Udacity (Bertelsmann Tech Booster Scholarship)
:::
:::::

::::: columns
::: {.column width="30%"}
**11/2023**
:::

::: {.column width="70%"}
[Become a Data Scientist](https://www.linkedin.com/learning/certificates/a8cb4dcb38e682fadb35ccadec6c3854fe1390f4b34cc9c394101932e49d2a14) - LinkedIn Certificate of Completion
:::
:::::

::::: columns
::: {.column width="30%"}
**11/2023**
:::

::: {.column width="70%"}
[Data Analyst in R](https://www.datacamp.com/statement-of-accomplishment/track/f83b8a7170216f6213f95199dbe791b4bc0984dc?raw=1) - DataCamp Statement of Accomplishment
:::
:::::

::::: columns
::: {.column width="30%"}
**07/2023**
:::

::: {.column width="70%"}
Essex Summer School in Social Science Data Analysis: Advanced Methods for Social Media and Textual Data in R
:::
:::::

::::: columns
::: {.column width="30%"}
**08/2022**
:::

::: {.column width="70%"}
Essex Summer School – [Machine Learning for Social Scientists](https://drive.google.com/file/d/11XGko4Jj8TSZkHLQPGPs6GnRGzHysWOR/view)
:::
:::::

------------------------------------------------------------------------

## **Formal Education**

::::: columns
::: {.column width="30%"}
**2019 – 2020**
:::

::: {.column width="70%"}
**Leiden University**, The Netherlands<br> Master of Science in Political Science<br> Subjects included: **Methods in Political Science**
:::
:::::

::::: columns
::: {.column width="30%"}
**2017 – 2019**
:::

::: {.column width="70%"}
**Central European University**, Budapest, Hungary<br> Master in Social Sciences with distinction<br> Subjects included: **Applied Statistics, Multivariate Statistics, Methods of Social Research**
:::
:::::

::::: columns
::: {.column width="30%"}
**2012 – 2016**
:::

::: {.column width="70%"}
**University of Novi Sad**, Serbia<br> Bachelor with Honours in Psychology<br> Subjects included: **Advanced Statistics, Experimental Research, Survey Techniques**
:::
:::::
